### ISSUE TITLE
ReadTheDocs PR CI: PDFLATEX flake

### ISSUE THREAD

**Issue by chukarsten** [alteryx/evalml#2355] opened 2021-06-09 18:06 UTC
Something weird is happening with the latex rendering engine on RTD.  There's a periodic failure that occurs in a flakey fashion that seems to fail RTD builds.

https://readthedocs.com/projects/feature-labs-inc-evalml/builds/651380/
https://readthedocs.com/projects/feature-labs-inc-evalml/builds/651420/

Scrolling down past the file extension errors and hyper reference errors, you find: 
```
!  ==> Fatal error occurred, no output PDF file produced!
Transcript written on feature-labs-inc-evalml.log.
Latexmk: Index file 'feature-labs-inc-evalml.idx' was written
Rule 'makeindex feature-labs-inc-evalml.idx': File changes, etc:
   Non-existent destination files:
      'feature-labs-inc-evalml.ind'
```

This seems to occur three times for three rules that fail.

**Comment by freddyaboulton** [comment] 2021-06-09 18:33
Has anyone seen this on a pr build or just main? I wonder if it's a difference in the build environments

**Comment by chukarsten** [comment] 2021-06-09 19:08
I didn't even see it on the PR build for the very last merge to main, the release branch.  Which is weird....but I tried wiping main and will try again.

**Comment by chukarsten** [comment] 2021-06-09 22:17
The last main I see that's passing is after Parthiv's #2344.  It seems that #2256 got merged after that and since then, main has not passed RTD.  We might need a nightly RTD build, at least.  Not sure why this is happening.

**Comment by chukarsten** [comment] 2021-06-10 00:44
Ran this draft PR to try and re-check #2256 's RTD which triggered [the build](https://readthedocs.com/projects/feature-labs-inc-evalml/builds/651799/) and it completed.

**Comment by freddyaboulton** [comment] 2021-06-15 15:27
@chukarsten I think we can close this?

**Comment by dsherry** [comment] 2021-06-17 17:36
@chukarsten confirmed, closing !

**Comment by dsherry** [comment] 2021-06-17 17:37
Quick note: this was caused by an extra tick mark in our release notes 🤯 #2368

**Closed by dsherry** 2021-06-17 17:36 UTC
Labels: bug, documentation, testing
