### ISSUE TITLE
Sample code change in README.md

### ISSUE THREAD

**Issue by moezali1** [alteryx/evalml#2002] opened 2021-03-22 02:01 UTC
Hi,

Following code base in README.md to be replaced:

```
import evalml
X, y = evalml.demos.load_breast_cancer()
X_train, X_test, y_train, y_test = evalml.preprocessing.split_data(X, y)
``` 

With:

```
import evalml
X, y = evalml.demos.load_breast_cancer()
X_train, X_test, y_train, y_test = evalml.preprocessing.split_data(X, y, problem_type = 'binary')
```

**Comment by freddyaboulton** [comment] 2021-07-27 14:04
Closing because this is a duplicate of #2106. This got fixed in #2108 !

**Closed by freddyaboulton** 2021-07-27 14:04 UTC
Labels: documentation, enhancement, good first issue
