### ISSUE TITLE
`partial_dependence` with ensembles errors

### ISSUE THREAD

**Issue by angela97lin** [alteryx/evalml#2712] opened 2021-08-30 20:46 UTC
Currently, trying to run `partial_dependence` with a stacked ensemble pipeline will raise the following error:

```

PartialDependenceError                    Traceback (most recent call last)
<ipython-input-12-4f356ba3e6ad> in <module>
      3     partial_dependence,
      4 )
----> 5 graph_partial_dependence(ensemble, X, 'Sex')

~/Desktop/evalml/evalml/model_understanding/graphs.py in graph_partial_dependence(pipeline, X, features, class_label, grid_resolution, kind)
    996 
    997     part_dep = partial_dependence(
--> 998         pipeline, X, features=features, grid_resolution=grid_resolution, kind=kind
    999     )
   1000 

~/Desktop/evalml/evalml/model_understanding/graphs.py in partial_dependence(pipeline, X, features, percentiles, grid_resolution, kind)
    856             raise PartialDependenceError(
    857                 str(e), PartialDependenceErrorCode.ALL_OTHER_ERRORS
--> 858             ) from e
    859 
    860 

PartialDependenceError: feature_importance is not implemented for SklearnStackedEnsembleClassifier and SklearnStackedEnsembleRegressor

```

This is because our ensemble estimator wraps a scikit-learn estimator using `scikit_learn_wrapped_estimator`. Within our wrapper classes, we call:
```
        if pipeline._is_fitted:
            self.feature_importances_ = pipeline.feature_importance
            self._is_fitted = True
            self.classes_ = pipeline.classes_
```

For a fitted ensemble, calling `self.feature_importances_ = pipeline.feature_importance` will error out since our ensemble does not support feature_importance (calling ensemble_pipeline.feature_importance throws an error).

As a fix, we should not try to set this attribute for ensemble components! Instead, however, we will need another attribute that ends with an underscore, such as attribute_; this is because partial dependence can only be calculated on fitted components, and scikit-learn considers a component that ends in a underscore as a fitted component.

This issue tracks adding a test for calculating partial dependence with ensembles and resolving this bug :)

**Comment by freddyaboulton** [comment] 2021-08-30 20:47
Is this a dupe of #2121 ?

**Closed** 2021-08-31 23:34 UTC
Labels: bug
