### ISSUE TITLE
Lead scoring demo search errors out

### ISSUE THREAD

**Issue by angela97lin** [alteryx/evalml#1492] opened 2020-12-02 18:26 UTC
https://evalml.alteryx.com/en/stable/demos/lead_scoring.html#Search-for-best-pipeline

Scores are all NaN.

**Comment by freddyaboulton** [comment] 2020-12-02 18:32
Seems to be related to the `TfidfVectorizer` called within `LSA` in the `TextFeaturizer` ?

https://stackoverflow.com/questions/39303912/tfidfvectorizer-in-scikit-learn-valueerror-np-nan-is-an-invalid-document

**Comment by freddyaboulton** [comment] 2020-12-11 18:12
I guess we'll have to wait until #1520 to verify but I think we can close this? The issue was related to the `TextFeaturizer` but in #1466 we changed the types to categorical so the `TextFeaturizer` is no longer being used.

We should probably get to the root cause of the stack trace though.

**Comment by freddyaboulton** [comment] 2020-12-15 16:41
I think the root cause is that there are NaNs in the `job` column and this causes the `TfidfVectorizer` in LSA to crash. You can reproduce this locally:

```python
from sklearn.feature_extraction.text import TfidfVectorizer
import pandas as pd
import woodwork as ww
from urllib.request import urlopen
customers_data = urlopen('https://featurelabs-static.s3.amazonaws.com/lead_scoring_ml_apps/customers.csv')
interactions_data = urlopen('https://featurelabs-static.s3.amazonaws.com/lead_scoring_ml_apps/interactions.csv')
leads_data = urlopen('https://featurelabs-static.s3.amazonaws.com/lead_scoring_ml_apps/previous_leads.csv')
customers = pd.read_csv(customers_data)
interactions = pd.read_csv(interactions_data)
leads = pd.read_csv(leads_data)

X = customers.merge(interactions, on='customer_id').merge(leads, on='customer_id')
y = X['label']
X = X.drop(['customer_id', 'date_registered', 'birthday','phone', 'email',
            'owner', 'company', 'id', 'time_x',
            'session', 'referrer', 'time_y', 'label', 'country'], axis=1)
TfidfVectorizer().fit_transform(X['job'])
```

Dropping NaNs fixes the issue:
![image](https://user-images.githubusercontent.com/41651716/102243772-85daf500-3ec9-11eb-81ec-47d473c9630b.png)


All of our AutoML pipelines have an Imputer. So I think the true bug is that the imputer does not impute NaNs for the `job` column!

![image](https://user-images.githubusercontent.com/41651716/102244251-0c8fd200-3eca-11eb-8499-c20d3fba7429.png)


I think we should do the following:
1. Close this issue and file an issue to track why the imputer does not impute values for the job column.
2. Interestingly, the `LSA` transformer comes after the `nlp_primitives` are finished computing features. That makes me think that the `nlp_primitives` DFS naturally handle NaNs  whereas `LSA` does not. Should that feature be added to LSA @eccabay ?

**Comment by angela97lin** [comment] 2020-12-19 07:07
@freddyaboulton Just checked, and looks like this is no longer an issue on `latest`: https://evalml.alteryx.com/en/latest/demos/lead_scoring.html#Search-for-best-pipeline

Still, what you pointed out is still a valid issue, if I'm understanding correctly. Should we repurpose this issue/open a new one to address this?

**Comment by freddyaboulton** [comment] 2020-12-21 14:48
@angela97lin I think it'll be clearest if we close out this issue and create a new one from my previous comment with the reproducer. So I'll do that now!

**Closed by freddyaboulton** 2020-12-21 14:48 UTC
