### ISSUE TITLE
Add error-handling to predict/predict_proba: check if feature names / logical types match those seen during fit

### ISSUE THREAD

**Issue by angela97lin** [alteryx/evalml#2855] opened 2021-09-28 21:41 UTC
Using the reproducer here: https://github.com/alteryx/evalml/issues/2475

The error I get after @freddyaboulton's changes in https://github.com/alteryx/evalml/pull/2834 are:

```
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-7-3bcc702bb569> in <module>
----> 1 pipeline.predict(holdout)

~/Desktop/evalml/evalml/pipelines/pipeline_meta.py in _check_for_fit(self, *args, **kwargs)
     31                 )
     32 
---> 33             return method(self, *args, **kwargs)
     34 
     35         return _check_for_fit

~/Desktop/evalml/evalml/pipelines/classification_pipeline.py in predict(self, X, objective, X_train, y_train)
    103             pd.Series: Estimated labels.
    104         """
--> 105         predictions = self._predict(X, objective=objective)
    106         predictions = pd.Series(
    107             self._decode_targets(predictions), name=self.input_target_name

~/Desktop/evalml/evalml/pipelines/binary_classification_pipeline.py in _predict(self, X, objective)
     50         if self.threshold is None:
     51             return self.component_graph.predict(X)
---> 52         ypred_proba = self.predict_proba(X)
     53         predictions = self._predict_with_objective(X, ypred_proba, objective)
     54         return infer_feature_types(predictions)

~/Desktop/evalml/evalml/pipelines/pipeline_meta.py in _check_for_fit(self, *args, **kwargs)
     31                 )
     32 
---> 33             return method(self, *args, **kwargs)
     34 
     35         return _check_for_fit

~/Desktop/evalml/evalml/pipelines/binary_classification_pipeline.py in predict_proba(self, X, X_train, y_train)
     65             pd.Series: Probability estimates
     66         """
---> 67         return super().predict_proba(X)
     68 
     69     @staticmethod

~/Desktop/evalml/evalml/pipelines/pipeline_meta.py in _check_for_fit(self, *args, **kwargs)
     31                 )
     32 
---> 33             return method(self, *args, **kwargs)
     34 
     35         return _check_for_fit

~/Desktop/evalml/evalml/pipelines/classification_pipeline.py in predict_proba(self, X, X_train, y_train)
    127                 "Cannot call predict_proba() on a component graph because the final component is not an Estimator."
    128             )
--> 129         X = self.compute_estimator_features(X, y=None)
    130         proba = self.estimator.predict_proba(X)
    131         proba = proba.ww.rename(

~/Desktop/evalml/evalml/pipelines/pipeline_base.py in compute_estimator_features(self, X, y, X_train, y_train)
    268             pd.DataFrame: New transformed features.
    269         """
--> 270         return self.component_graph.compute_final_component_features(X, y=y)
    271 
    272     def _fit(self, X, y):

~/Desktop/evalml/evalml/pipelines/component_graph.py in compute_final_component_features(self, X, y)
    213             pd.DataFrame: Transformed values.
    214         """
--> 215         features, _ = self._fit_transform_features_helper(False, X, y)
    216         return features
    217 

~/Desktop/evalml/evalml/pipelines/component_graph.py in _fit_transform_features_helper(self, needs_fitting, X, y)
    236             y=y,
    237             fit=needs_fitting,
--> 238             evaluate_training_only_components=needs_fitting,
    239         )
    240         x_inputs, y_output = self._consolidate_inputs_for_component(

~/Desktop/evalml/evalml/pipelines/component_graph.py in _compute_features(self, component_list, X, y, fit, evaluate_training_only_components)
    370                     output = x_inputs, y_input
    371                 else:
--> 372                     output = component_instance.transform(x_inputs, y_input)
    373 
    374                 if isinstance(output, tuple):

~/Desktop/evalml/evalml/pipelines/components/component_base_meta.py in _check_for_fit(self, X, y)
     38                 return method(self)
     39             elif y is None:
---> 40                 return method(self, X)
     41             else:
     42                 return method(self, X, y)

~/Desktop/evalml/evalml/pipelines/components/transformers/imputers/imputer.py in transform(self, X, y)
    129         if self._categorical_cols is not None and len(self._categorical_cols) > 0:
    130             X_categorical = X.ww[self._categorical_cols.tolist()]
--> 131             imputed = self._categorical_imputer.transform(X_categorical)
    132             X_no_all_null[X_categorical.columns] = imputed
    133 

~/Desktop/evalml/evalml/pipelines/components/component_base_meta.py in _check_for_fit(self, X, y)
     38                 return method(self)
     39             elif y is None:
---> 40                 return method(self, X)
     41             else:
     42                 return method(self, X, y)

~/Desktop/evalml/evalml/pipelines/components/transformers/imputers/simple_imputer.py in transform(self, X, y)
     96         )
     97 
---> 98         X_t = self._component_obj.transform(X)
     99         X_t = pd.DataFrame(X_t, columns=not_all_null_cols)
    100         if not_all_null_cols:

~/Desktop/evalml_venv/lib/python3.7/site-packages/sklearn/impute/_base.py in transform(self, X)
    482                 mask_valid_features = missing_mask
    483             else:
--> 484                 mask_valid_features = missing_mask[:, valid_statistics_indexes]
    485             n_missing = np.sum(mask_valid_features, axis=0)
    486             values = np.repeat(valid_statistics, n_missing)

TypeError: 'bool' object is not subscriptable

```

However, I don't think it's a partial dependence bug since calling just `pipeline.predict(holdout)` errors out.

**Comment by freddyaboulton** [comment] 2021-09-28 21:54
@angela97lin I think you are right that it has nothing to do with partial dependence:

If I change the repro to this

```python
import pandas as pd
from evalml import AutoMLSearch

path = "/Users/freddy.boulton/Downloads/string_nan_ex/1625078186889-mushroom_subset.csv"

df = pd.read_csv(path)
y_train = df['class']
X_train = df.drop('class', axis=1)

aml = AutoMLSearch(X_train, y_train, 'binary')
aml.search()


pipeline = aml.best_pipeline
holdout = pd.read_csv("/Users/freddy.boulton/Downloads/string_nan_ex/mushroom_holdout.csv")
pipeline.predict(holdout)
```

I get the same error on `pipeline.predict(holdout)`.

**Comment by freddyaboulton** [comment] 2021-09-28 23:27
@angela97lin I think I know what the problem is:

In `X_train` the `odor` feature is of logical type `Category` but in `holdout` it is `Unknown`.

Adding 
```python
holdout.ww.init(logical_types={"odor": "Categorical"})
```
to the original partial dependence repro (provided you're on the feature branch of #2834) will remove the error! 

So I think the more general error is "Can't predict on pipelines where logical types do not match those seen during fit".

**Comment by freddyaboulton** [comment] 2021-11-09 22:31
@alteryx/evalml I'm moving this to the current sprint. I'm thinking this is a quick fix that could make our users lives a lot better.

We oftentimes get user stacktraces deep from within a pipeline, going as far down as sklearn even, and most of the time that scary stacktrace is because the logical types are not preserved from fit to predict. 

Providing a clear error message might help users understand what went wrong and even help them fix the issue!

**Closed** 2021-11-17 22:57 UTC
Labels: bug
