### ISSUE TITLE
TargetLeakageDataCheck is not working for regression 

### ISSUE THREAD

**Issue by tyler3991** [alteryx/evalml#1937] opened 2021-03-05 21:28 UTC
Woodwork mutual information is causing TargetLeakageDataCheck to have weird behavior

**Comment by freddyaboulton** [comment] 2021-03-05 21:44
For some more context:

evalml currently uses mutual info to measure the association between the target and all features in our `TargetLeakageDataCheck`. 

As of woodwork `0.10.0`, woodwork does not calculate mutual info for columns that have all unique values. 

This is probably fine for classification but not great for regression cause the target could (and probably has) all unique values. That means that the evalml `TargetLeakageDataCheck` is not really doing anything for regression problems.

This new behavior is also causing problems for our `MulticollinearityDataCheck` since it also leverages woodwork's mutual information function. This means we are not able to detect multicollineatirybetween numeric features that have all unique values.

**Comment by angela97lin** [comment] 2021-03-15 18:06
I believe this is blocked / resolved by #1980?

**Comment by freddyaboulton** [comment] 2021-03-15 18:14
Yea updating woodwork to 0.11.0 should fix this problem @angela97lin !

**Comment by angela97lin** [comment] 2021-03-18 17:31
@freddyaboulton Thanks for the confirmation! I'll mark this as blocked by #1980. This issue will track confirming that #1980 resolves this behavior.

**Comment by angela97lin** [comment] 2021-03-19 15:42
Just tried with this test on main:
```
from evalml.data_checks import (
    DataCheckMessageCode,
    DataCheckWarning,
    MulticollinearityDataCheck
)
X = pd.DataFrame({'col_1': ["a", "b", "c", "d", "e"],
                      'col_2': ["w", "x", "y", "z", "b"],
                      'col_3': ["a", "a", "c", "d", "a"],
                      'col_4': ["a", "b", "c", "d", "a"],
                      'col_5': ["0", "0", "1", "2", "0"],
                      'col_6': [1, 2, 3, 4, 5],
                      'col_7': [.1, .2, .3, .4, .5]
                  
                      })
multi_check = MulticollinearityDataCheck(threshold=0.9)
multi_check.validate(X)
```
This returned 

```
{'warnings': [{'message': "Columns are likely to be correlated: [('col_1', 'col_2'), ('col_1', 'col_6'), ('col_1', 'col_7'), ('col_2', 'col_6'), ('col_2', 'col_7'), ('col_3', 'col_5'), ('col_6', 'col_7'), ('col_1', 'col_4'), ('col_2', 'col_4'), ('col_4', 'col_6'), ('col_4', 'col_7')]",
   'data_check_name': 'MulticollinearityDataCheck',
   'level': 'warning',
   'code': 'IS_MULTICOLLINEAR',
   'details': {'columns': [('col_1', 'col_2'),
     ('col_1', 'col_6'),
     ('col_1', 'col_7'),
     ('col_2', 'col_6'),
     ('col_2', 'col_7'),
     ('col_3', 'col_5'),
     ('col_6', 'col_7'),
     ('col_1', 'col_4'),
     ('col_2', 'col_4'),
     ('col_4', 'col_6'),
     ('col_4', 'col_7')]}}],
 'errors': [],
 'actions': []}
```

which is evidence that mutual information for columns with completely unique values (ex: col_6, col_7) are being calculated again! Thus, I think we can close this issue :D

**Closed by angela97lin** 2021-03-19 15:42 UTC
Labels: bug
