### ISSUE TITLE
Getting Error when installing . Please help

### ISSUE THREAD

**Issue by AmitKumar0106** [alteryx/evalml#3174] opened 2021-12-29 07:45 UTC
I am getting below error when installing in kaggle :
ERROR: Cannot uninstall 'llvmlite'. It is a distutils installed project and thus we cannot accurately determine which files belong to it which would lead to only a partial uninstall.

pip install evalml
!pip install evalml

Also restarted session still not able to import evalml

**Comment by chukarsten** [comment] 2022-01-03 16:53
@AmitKumar0106 I can verify that I'm getting the same thing trying to install evalml within the kaggle jupyter notebook.  I'm currently trying to reproduce in a python 3.7.12 environment locally!

**Comment by chukarsten** [comment] 2022-01-03 18:29
@AmitKumar0106 this issue is actually tracked in #2671 .  What's happening is that the kaggle docker image installs a version of another python library, numba, that is incompatible with evalml.  Numba has actually merged a fix, but we're waiting on them to release this fix.  When numba releases and the kaggle docker image updates to this version, installing evalml in a jupyter notebook cell on kaggle shouldn't be an issue.

In the meantime, however, I'm trying a few things to get you up and running with evalml immediately: 
1.) !conda install evalml -y
2.) !conda install numba=0.53 -y THEN !conda install evalml -y

The conda install directive seems to work within kaggle's ipython env but I can't seem to send the "Yes" flag successfully.

**Comment by chukarsten** [comment] 2022-02-02 19:56
Closing due to inactivity.

**Closed by chukarsten** 2022-02-02 19:56 UTC
Labels: bug
