### ISSUE TITLE
Docs take much longer to build

### ISSUE THREAD

**Issue by angela97lin** [alteryx/evalml#1627] opened 2020-12-30 21:28 UTC
I noticed that docs have been taking much longer to build. I think this is likely because the automl docs were changed in https://github.com/alteryx/evalml/commit/c871f3b4622f133e8c547b7081964326a3bc693d to use the fraud dataset, instead of the breast cancer data set (+ elsewhere?) to showcase `infer_problem_types`, since the breast cancer dataset only has numeric columns.

**Comment by dsherry** [comment] 2021-01-04 14:16
I think the main reason for this is that we changed the defaults for automl, from `n_iterations=5` to `n_batches=1` which will now run 9 pipelines.

Closing as a duplicate of #1420

**Closed by dsherry** 2021-01-04 14:16 UTC
