### ISSUE TITLE
ComponentGraph does not respect dag structure

### ISSUE THREAD

**Issue by freddyaboulton** [alteryx/evalml#2257] opened 2021-05-11 22:22 UTC
This came up during #2046

Repro
```python
from evalml.pipelines import Transformer, ComponentGraph
from evalml.utils import infer_feature_types
from sklearn.datasets import make_regression
import pytest
import numpy as np


class LogTransform(Transformer):
    name = "Log Transform"

    def __init__(self, parameters=None, random_seed=0):
        super().__init__(parameters={}, component_obj=None, random_seed=random_seed)

    def fit(self, X, y):
        return self

    def transform(self, X, y=None):
        if y is None:
            return X, y
        y = infer_feature_types(y)
        return X, infer_feature_types(np.log(y.to_series()))

    def inverse_transform(self, X, y=None):
        y = infer_feature_types(y)
        return X, infer_feature_types(np.exp(y.to_series()))


cg = ComponentGraph({"Imputer": ['Imputer'],
                     "Log": [LogTransform],
                     "ET": ["Extra Trees Regressor", "Imputer.x", "Log.y"],
                     "Log 2": [LogTransform],
                     "RandomForest": ["Random Forest Regressor", "Imputer.x", "Log 2.y"],
                     "Log 3": [LogTransform],
                     "Catboost": ["CatBoost Classifier", "Imputer.x", "Log 3.y"],
                     "Logistic Regression": ["Logistic Regression Classifier", "Catboost", "RandomForest", "ET"]})

X, y = make_regression(n_samples=100, n_features=20, n_informative=3, random_state=0)
y = np.abs(y)
X = np.abs(X)

with pytest.raises(ValueError, match='Input contains NaN'):
    cg.instantiate({})
    cg.fit(X, y)
```

The problem is that the component graph uses the output of the "previous component" when the given component has no y parent ([code](https://github.com/alteryx/evalml/blob/main/evalml/pipelines/component_graph.py#L234)).

In this particular case, that means that the random forest gets a target that's been logged twice (as opposed to once) and taking the log twice in this case creates nans (because after the first log, some values are negative).

![image](https://user-images.githubusercontent.com/41651716/117892353-95971380-b286-11eb-8ba5-dc8d158ef635.png)

**Comment by freddyaboulton** [comment] 2021-06-07 15:34
@dsherry @chukarsten Can we prioritize this for one of the next two coming sprints?

**Comment by angela97lin** [comment] 2021-08-09 16:19
@freddyaboulton I couldn't repro the example code directly since I'm not certain about the Logistic Regression Classifier being the final estimator and the ComponentGraph API has changed since this issue was filed, but I ran the following:

```python
from evalml.pipelines import Transformer, ComponentGraph
from evalml.utils import infer_feature_types
from sklearn.datasets import make_regression
import pytest
import numpy as np


class LogTransform(Transformer):
    name = "Log Transform"

    def __init__(self, parameters=None, random_seed=0):
        super().__init__(parameters={}, component_obj=None, random_seed=random_seed)

    def fit(self, X, y):
        return self

    def transform(self, X, y=None):
        if y is None:
            return X, y
        y = infer_feature_types(y)
        return X, infer_feature_types(np.log(y))

    def inverse_transform(self, X, y=None):
        y = infer_feature_types(y)
        return X, infer_feature_types(np.exp(y))


cg = ComponentGraph({"Imputer": ['Imputer', 'X', 'y'],
                     "Log": [LogTransform, 'X', 'y'],
                     "ET": ["Extra Trees Regressor", "Imputer.x", "Log.y"],
                     "Log 2": [LogTransform, 'X', 'y'],
                     "RandomForest": ["Random Forest Regressor", "Imputer.x", "Log 2.y"],
                     "Log 3": [LogTransform, 'X', 'y'],
                     "Catboost": ["CatBoost Regressor", "Imputer.x", "Log 3.y"],
                     "Random Forest Regressor": ["Random Forest Regressor", "Catboost.x", "RandomForest.x", "ET.x", 'y']})

X, y = make_regression(n_samples=100, n_features=20, n_informative=3, random_state=0)
y = np.abs(y)
X = np.abs(X)

cg.instantiate({})
cg.fit(X, y)
cache = cg._compute_features(cg.compute_order, X, y, fit=True)
print (cache['Log.y'])
print (cache['Log 2.y'])
print (cache['Log 3.y'])
```

To double check, `cache['Log.y']` == `cache['Log 2.y']`  == `cache['Log 3.y']` == `np.log(y)`. This was previously not the case since the first Log transformer would store np.log(y) as the most recent y (causing the estimators to get a y value that was doubly log'ed).

I think we can safely close this issue!

**Closed by angela97lin** 2021-08-09 16:19 UTC
Labels: bug

**Comment by freddyaboulton** [comment] 2021-08-09 18:36
Thank you @angela97lin !!
