### ISSUE TITLE
TargetEncoder: preserve custom row index

### ISSUE THREAD

**Issue by angela97lin** [alteryx/evalml#1723] opened 2021-01-22 04:36 UTC
The TargetEncoder currently calls:
```
        if isinstance(X, pd.DataFrame):
            X.reset_index(drop=True, inplace=True)
        if isinstance(y, pd.Series):
            y.reset_index(drop=True, inplace=True)
```
Is this what we want? Previously, there were other components such as the Imputer where resetting the index caused issues.

@freddyaboulton I see that there was some discussion on https://github.com/alteryx/evalml/pull/1401#discussion_r523162379; I'd love to hear your thoughts!

**Comment by freddyaboulton** [comment] 2021-01-22 15:49
@angela97lin Yea I agree this is a bug because the TargetEncoder changes the index on X after fitting:

![image](https://user-images.githubusercontent.com/41651716/105511985-950a4b00-5c9e-11eb-864a-e1da49fec1cf.png)

The problem is that the encoder will raise an exception with ugly stacktrace if the indices between `X` and `y` aren't equal. So maybe we have two options:

1) Raise the exception ourselves if the indices aren't equal
2) If the indices aren't equal, reset the index with `inplace=False`

2) is closer to our current behavior so maybe we should go with that but the downside is that it copies the data. 

Out of scope for this issue but I'm curious what your thoughts are on catching mismatched indices earlier in the "modeling process" maybe with a datacheck? I'm starting to think that's something we shouldn't allow.

**Comment by angela97lin** [comment] 2021-01-22 18:25
@freddyaboulton Wow, thank you for this! 

I guess this is a bit trickier than our other components which, although take in `y`, don't necessarily use it for fitting/transforming, so we've always just carried the X index around. But is there ever a reason why a user would pass in mismatched indices intentionally? If no, then perhaps we should go with 1. If we provide a clear enough exception message, then it shouldn't be too much trouble for a user to reset the indices on their own, and because they have to manually do it, they'll be aware of the operation that's happening.

I like the idea of adding some data check for mismatched indices! I'll file an issue for that 😁

**Comment by dsherry** [comment] 2021-01-28 18:32
Let's jump on a call sometime soon and discuss this. Can we find a solution which will apply to all components? It would be great if we found a way to avoid more custom index issues in the future.

**Comment by dsherry** [comment] 2021-02-02 18:28
Discussion with @angela97lin @freddyaboulton cleared this up a bunch, ready to go.

**Questions**
* Why should we preserve custom indices?
    * A: if we don't, we'll get bugs where components downstream have mismatched indices with orig input. Also, if the user set custom index, components in the pipelines should ideally respect those indices, so that user-defined code could expect custom indices.
* Should components preserve custom indices? A: yes
* What if indices in X and y don't match? A: add data check
* What do we do if components change indices under the hood? A: punt on this, disallow for now.
* Which components don't respect custom indices today?
    * Target encoder. Pandas logic didn't match the indices. We're doing a reset right now.
    * Imputer, but we've since fixed that.

**Next steps**
* RE X/y input row index not matching: add datacheck for automl for when indices of X and y don't match. Don't add error handling for pipelines/components. Tracked by #1779 .
* RE components handling custom row index:
    * Policy: all components should output the same row index as was provided as input.
    * Fix target encoder to respect custom indices
    * Add custom index test coverage which iterates over all components (which includes future ones)
    * This issue tracks this work

**Closed** 2021-02-12 18:55 UTC
Labels: bug
