### ISSUE TITLE
Typo / Error in Fraud Tutorial 

### ISSUE THREAD

**Issue by moezali1** [alteryx/evalml#2069] opened 2021-04-01 14:59 UTC
Hi,

Tutorial Link: https://evalml.alteryx.com/en/stable/demos/fraud.html

The hold-out AUC on the `fraud_optimized` pipeline is still better than AUC on the `auc_optimized`. Although, the difference is very immaterial 0.8739 vs. 0.8762. In light of that, you may want to reword the first paragraph a little bit.

I principally agree with the point being demonstrated in this tutorial, it just happens to be a "not-so-materially" different in this particular example.

![image](https://user-images.githubusercontent.com/54699234/113305939-8b6e1680-92d1-11eb-8c3c-14815e1ae9bd.png)

**Comment by dsherry** [comment] 2021-04-01 18:00
Thank you @moezali1 ! Yep it looks like something has shifted since we wrote this. We'll take a look.

**Comment by angela97lin** [comment] 2021-04-06 15:35
Note: might be a duplicate of https://github.com/alteryx/evalml/issues/1491

**Closed** 2021-04-20 16:28 UTC
Labels: bug, documentation
